### ISSUE TITLE
Endlessly generated log files

### ISSUE THREAD

**Issue by deetr-** [Lange/MGEMod#21]
MGEMod (version (2.0.9.2)) has been filling soucemod/logs error files with:

>L 10/25/2015 - 13:23:54: [SM] Call stack trace:
L 10/25/2015 - 13:23:54: [SM] Exception reported: Plugin not runnable

endlessly about 50 lines per second until the log file reaches 2GB then starts over as a new file.

`"MGEMod" (2.0.9.2) by Lange & Cprice; based on kAmmomod by Krolus.`
`SourceMod Version: 1.8.0.5717`
`SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5717)`
`SourcePawn API: v1 = 4, v2 = 10`
`Compiled on: Oct 24 2015 16:17:46`
`Built from: https://github.com/alliedmodders/sourcemod/commit/6042518`
`Build ID: 5717:6042518`

Full log:
>L 10/25/2015 - 13:23:53: [SM] Exception reported: Map not supported. MGEMod disabled.
L 10/25/2015 - 13:23:53: [SM] Blaming plugin: mgemod.smx
L 10/25/2015 - 13:23:53: [SM] Call stack trace:
L 10/25/2015 - 13:23:53: [SM] [0] SetFailState
L 10/25/2015 - 13:23:53: [SM] [1] Line 433, mgemod.sp::OnMapStart()
L 10/25/2015 - 13:23:54: [SM] Exception reported: Plugin not runnable
L 10/25/2015 - 13:23:54: [SM] Call stack trace:
L 10/25/2015 - 13:23:54: [SM] Exception reported: Plugin not runnable
L 10/25/2015 - 13:23:54: [SM] Call stack trace:

I think this may be related to this bug with timers https://bugs.alliedmods.net/show_bug.cgi?id=6338

**Comment by Lange** [comment]
Thanks for reporting this @deetr-.

I unfortunately no longer maintain MGEMod, so someone will need to submit a pull request for this.

**Comment by Arie** [comment]
As a work-around, use Sourcemod 1.7, where this is not an issue.

**Comment by Lange** [comment]
It sounds like this isn't a problem with Sourcemod@^1.7.0. Closing.
