### ISSUE TITLE
Completely black area on spawn and cannot use any MGE commands.

### ISSUE THREAD

**Issue by James76931** [Lange/MGEMod#24]
Hey,

Upon joining the server running MGE, I spawn in a black area with no light whatsoever. As well as this, I am unable to use any MGE commands.

I have seen other people with the same issue, but they never describe how they resolved it - it's either "Someone fixed it for me" or a forum post with no response.

If you'd be able to help, that would be great as I've been trying to install MGE and fix that issue for around 4 days now haha.

Thanks,
_- James_

**Comment by Cprice1771** [comment]
Generally this is due to the sourcemod plugin being broken or not installed properly. Please make sure that your sourcemod version is installed on your server and working properly: https://www.sourcemod.net/downloads.php?branch=stable

**Comment by James76931** [comment]
I'll take a look again.

**Comment by James76931** [comment]
Nevermind, my fault - for some reason my addons directory wasn't assigned the correct permissions.

Thank you anyway.
