### ISSUE TITLE
Snakewater map spawn issues

### ISSUE THREAD

**Issue by James76931** [Lange/MGEMod#25]
Occasionally when you are playing on the Snakewater arena - you will be spawned underneath the ground instead of in the actual arena. All the other maps seem to be ok but Snakewater isn't.

This doesn't seem to be an issue on my behalf unlike yesterday since it's a spawn issue.

Thanks,
- James

**Comment by walliski** [comment]
See from this how to fix it, real easy: #26. :) @Lange might want to merge the PR also.

**Comment by James76931** [comment]
Thank you very much for your help :)
