### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by James76931** [Lange/MGEMod#27]
Hey again.

For some odd reason, my console is being spammed with:
"DataTable warning: player: Out-of-range value (97364.218750/65536.000000) in SendPropFloat 'm_flLastDamageTime', clamping."

Thanks,
- James

**Comment by James76931** [comment]
(The number before the / does also keep changing)

**Comment by Lange** [comment]
Hi @James76931!

Unfortunately, I no longer maintain MGEMod. Hopefully a generous person will come along and be able to look into this for you.

**Comment by walliski** [comment]
What version of sourcemod are you running?

**Comment by James76931** [comment]
Hey,
I'm running SM version 1.7.3-dev+5279.

**Comment by walliski** [comment]
https://forums.alliedmods.net/showthread.php?t=194266

not sure if it has anything to do with mge?

**Comment by James76931** [comment]
Ah, thank you very much for your help once again.

By the way, I've noticed that the BBall 2v2 arena doesn't seem to spawn the intel... This may be just because there is one person in the arena and not all 4 players but I feel like this may be an issue caused by the plugin.

Thanks again,
_- James_

**Comment by Cprice1771** [comment]
I don't believe Intel spawns until the arena actually starts, there are some other known issues with bball where the collision events for capping would stop getting called if the server hadn't changed map for too long as well, so try playing with 4 people/restarting server and map if you have any more issues.

**Comment by James76931** [comment]
Alright, thank you. I will try that in a bit.

**Comment by James76931** [comment]
Well, it doesn't look like I can find anyone to test it atm so I'll have to test it another time. I'll also close this issue as the main issue has been dealt with and make a new one if there is an issue with the BBall.
