### ISSUE TITLE
!handicap command doesn't work after winning the point

### ISSUE THREAD

**Issue by mjpauly** [Lange/MGEMod#29]
Hi,
I found a bug with the handicap command where it doesn't clip your health after you win the point. You still gain the health buff you would normally receive if you weren't playing with the handicap. It works fine if you lost the point and died, however. I would very much appreciate it if it were working again. :)

**Comment by Lange** [comment]
Hi @mjpauly.

This repository is no longer maintained by me.

However, perhaps a generous person with some time to spare will see this issue and open a pull request, which I will gladly accept.

Best,
Lange

**Comment by mjpauly** [comment]
Ok! Thank you for all the time and effort you've put into it, Lange. It's a great mod. Best of luck with your future endeavors!
