### ISSUE TITLE
2 Vs 2 Winner/Loser Names Error

### ISSUE THREAD

**Issue by WakaFlocka789** [Lange/MGEMod#36]
Hello guys anytime you win 2 vs 2 1 of the winner name gets displayed also as a loser name here's an example {GPG} Mr.Smizer and Lucario Batfoxkid (Score:20) defeats Olitude and Lucario Batfoxkid (Score:1) in duel to 20 on Granary Middle [2 vs 2]

So i was on the same team as Smizer and we won my in game Name is {GPG} Waka Flocka Flame
but instead it thinks i'm lucario which is the loser team red team. This is a bug here's how it should be {GPG} Mr.Smizer and {GPG} Waka Flocka Flame (Score:20) defeats Olitude and Lucario Batfoxkid (Score:1) in duel to 20 on Granary Middle [2 vs 2]

if anyone knows a fix for the 2 vs 2 winner/loser names please post it thanks

**Comment by Lange** [comment]
Closed by #37
