### ISSUE TITLE
mgemod.smx file missing

### ISSUE THREAD

**Issue by PlayToNguyen** [Lange/MGEMod#55]
I don't know if this is intentional or not but I was just struggling for a while to install the MGE plugin (first time installing sourcemod mods) and the .smx file is just missing from the latest release. It took me a while and I just downloaded an old version (2.2.0) but 2.2.1 is missing the /addons/sourcemod/plugins folder entirely.  
  
Probably not a problem for someone updating, but this is the version (2.2.1) linked from https://forums.alliedmods.net/showthread.php?p=1448559 so anyone who is installing it for the first time may not identify the missing file.

**Comment by sapphonie** [comment]
https://github.com/Lange/MGEMod/releases/latest ?

**Comment by PlayToNguyen** [comment]
Ah maybe it was just something I misunderstood with Github I'm not sure. Is the source code different than the regular .zip? The source code doesn't have the .smx file, but maybe that's intentional. Either way, the download from the forums is the source code so it is missing the .smx file.

Here's a video to show it better than I can explain it:
https://www.youtube.com/watch?v=cuXYEeRvMdQ&feature=youtu.be

If nothing else, the download from https://forums.alliedmods.net/showthread.php?t=154755?t=154755 should probably be the .zip with the .smx file

**Comment by walliski** [comment]
Yeah, the source code is different from other zips that is in the release. Normally you do not commit autogenerated binaries (such as compiled code) to the repository. However, they used to do this before in this repo, but arent doing that anymore, which is probably why the link is wrong. You are correct though that the link should be updated!

If @Lange would want to update the forum post?
